eureka:
  client:
    serviceUrl:
      defaultZoneUrl: http://localhost:8761/eureka/
  instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#security:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:1033/users/current



logging:
  level:
    org.springframework.cloud: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.security: DEBUG
    org.springframework: DEBUG
    com.example.demo3: DEBUG